variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HATCH_DATA_DIR: "$CI_PROJECT_DIR/.hatch-data"
  PIP_ROOT_USER_ACTION: "ignore"
  HATCH_ENV_TYPE_VIRTUAL_PATH: ".venv"

cache:
  key:
    files:
      - pyproject.toml
    prefix: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - .hatch-data
    - .venv
  policy: pull-push

image: python:3.14-slim

before_script:
  - pip install --cache-dir .cache/pip hatch

test:
  stage: test
  script:
    - hatch run pytest
