from abc import ABC, abstractmethod
from typing import Literal, cast
import numpy as np
import cvxpy as cp
from time import time

from sklearn.model_selection import train_test_split
from ..weighting import SampleWeighting
from ..stopping import StoppingMethod

class DccpTrainer(ABC):
    """
    Abstract class for DCCP optimization using cvxpy.
    """

    def __init__(self, margin: float, validation_ratio: float,
                 weighting_method: SampleWeighting,
                 stopping_methods: list[StoppingMethod],
                 verbose: Literal[0, 1, 2],
                 random_state: np.random.RandomState) -> None:
        """
        Initialize the trainer.

        param validation_radio: How much of the training set to dedicate to use
                                as validation during fitting.
        param weighting_method: The weighting method to use: apply weights to
                                the cost contribution of each data point to help
                                avoid outliers.
        param stopping_methods: A list of stopping methods, must not be empty.
                                At each epoch, these methods will be
                                sequentially asked whether the training should
                                stop. In this case, training ends by rolling
                                back to the epoch with the best validation cost.
        param verbose:          Whether to log extra information. 0: no logging,
                                1: basic logging / timing, 2: cvxpy solve() set
                                to verbose mode.
        param random_state:     A RandomState object or None to allow for seeded
                                randomness.
        """

        if margin < 0:
            raise ValueError(f'Invalid margin, expected >= 0 but got {margin}')
        if not 0 <= validation_ratio < 1:
            raise ValueError('Invalid validation ratio, expected >= 0 and < 1 '
                             f'but got {validation_ratio}')
        if not len(stopping_methods):
            raise ValueError('Empty list of stopping methods, training would '
                             'run indefinitely')

        self.margin = margin
        self.validation_ratio = validation_ratio
        self.weighting_method = weighting_method
        self.stopping_methods = stopping_methods
        self.verbose = verbose
        self.random_state = random_state

    def at_training_start(self, data_dim: int) -> None:
        """
        Optional actions to take when the training starts.
        For example, create and persist a list of additional variables to
        optimize.
        """

    def after_epoch(self) -> None:
        """
        Optional additional actions to take after each epoch, that is after
        cvxpy solve() and during wrapping code.
        """

    def at_training_end(self) -> None:
        """
        Optional actions to take when the training is over.
        Ran as the very last function call in train, meaning after
        rollback_to_best is called.
        """

    @abstractmethod
    def save_best(self) -> None:
        """
        Paired with rollback_to_best.

        Save the data generated by after_epoch somewhere accessible at the
        end of the training process.

        Used in the training loop to roll back to the best state of the model at
        the end of the loop.
        """

    @abstractmethod
    def rollback_to_best(self) -> None:
        """
        Paired with save_best.

        Restore the state saved in save_best, after the training process is
        done, to go back to the best performing model.
        """

    @abstractmethod
    def get_problem(self, X: np.ndarray, y: np.ndarray,
                    cost_weights: np.ndarray) -> cp.Problem:
        """
        Compute a cvxpy Objective and a list of Constraints for use in DCCP.
        The prlblem must be DCP, meaning the constraints must all be convex.
        For concave constraints, they must be linearized beforehand, possibly
        from constant values taken from the previous epoch result.

        param X:             The data points
        param y:             The data points classes
        param cost_weights: The wdccp weights, all 1 if not using wdccp, for
                             use in computing the objective.
                             This is an array with one element corresponding to
                             an element in X.

        return:              A tuple containing a cvxpy Objective and a list of
                             Constraints.
        """

    @abstractmethod
    def get_cost(self, X: np.ndarray, y: np.ndarray) -> float:
        """
        Compute the cost for a set of sample points in the same way as the cost
        defined in get_problem, used in train/validation training.

        Can use the weights computed in this epoch's after_epoch call,
        made right before this call.
        """

    def train(self, X: np.ndarray, y: np.ndarray) -> None:
        """
        Train using DCCP.
        This means this function can only solve problems where the cost function
        can be separable in the given convex and concave parts.

        param X: The set of data points to use for training.
        param y: The set of labels associated with elements of X.

        return:  The final cost, or -1 if no training happened.
        """

        if self.verbose:
            print('Starting fitting with DCCP')

        no_validation = self.validation_ratio == 0
        if no_validation:
            for stopping_method in self.stopping_methods:
                if stopping_method.requires_validation():
                    raise ValueError('Cannot train, at least one stopping '
                                     'method requires validation which is '
                                     'disabled by the user')

            X_train, X_validation = X, np.empty(X.shape)
            y_train, y_validation = y, np.empty(y.shape)
        else:
            X_train, X_validation, y_train, y_validation = train_test_split(
                    X, y, test_size=self.validation_ratio)
            X_train = cast(np.ndarray, X_train)
            X_validation = cast(np.ndarray, X_validation)
            y_train = cast(np.ndarray, y_train)
            y_validation = cast(np.ndarray, y_validation)

        if not X_train.size or (not X_validation.size and not no_validation):
            raise ValueError('Current validation ratio makes unwanted '
                             'degenerate train/validation split: '
                             + str(self.validation_ratio))

        start = time()
        cost_weights, cost_normalizer = \
                self.weighting_method.fit_transform(X_train, y_train)

        epoch = 1
        validation_cost: float = np.inf
        best_validation_cost: float = np.inf

        # formulate the cvxpy problem to solve, common to all epochs
        self.at_training_start(X_train.shape[1])

        while True:
            problem = self.get_problem(X_train, y_train, cost_weights)

            # solve the problem, normalize the cost when using wdccp
            cvxpy_cost = cast(float, problem.solve(verbose=self.verbose == 2)) \
                    * cost_normalizer

            if self.verbose:
                print(f'Epoch {epoch}, cost: {cvxpy_cost:.8f}')

            self.after_epoch()

            # best score and loop logic
            done = False
            if no_validation:
                train_cost = cvxpy_cost
                validation_cost = cvxpy_cost
            else:
                train_cost = self.get_cost(X_train, y_train)
                validation_cost = self.get_cost(X_validation, y_validation)
            if validation_cost < best_validation_cost:
                best_validation_cost = validation_cost
                self.save_best()

            for stopping_method in self.stopping_methods:
                if stopping_method.should_stop(
                        epoch, train_cost, validation_cost):
                    done = True
                    break

            if done:
                break

            epoch += 1

        if self.verbose:
            dt = time() - start
            print(f'DCCP done in {epoch} epochs, '
                  f'final cost is {validation_cost:.8f} in {dt:.2f}s')

        self.rollback_to_best()
        self.at_training_end()
