name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Hatch
        run: pip install -U pip hatch

      - name: Run tests
        run: hatch run pytest

  todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for TODOs in the code
        run: ./check_todos.sh
