name: Deploy package to PyPI

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

concurrency:
  group: "deploy-pypi"
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/reusable_tests.yml

  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    needs:
      - test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
