name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write
      contents: read

    container:
      image: python:3.14-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch

      - name: Build package
        run: hatch build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
