name: Reusable testsuite

on:
  workflow_call:

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        # also test on other OSes, but not for all versions to save minutes
        include:
          - os: windows-latest
            python-version: "3.13"
          - os: macos-latest
            python-version: "3.13"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }} with uv
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dccp --group test

      - name: Run tests
        run: uv run --frozen pytest -n 5
