name: Testsuite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    name: Coverage test (ignore failed tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Hatch
        run: pip install hatch

      - name: Install coverage utilities
        run: pip install coverage

      - name: Check coverage
        run: |
          hatch run pytest --cov --cov-fail-under=90

  test-versions:
    name: With Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch

      - name: Run tests with Hatch
        run: hatch run test.py${{ matrix.python-version }}:pytest
