name: Testsuite

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: "testsuite"
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/reusable_tests.yml

  coverage:
    name: Coverage test (ignore failed tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: pip install -U pip hatch coverage

      - name: Check coverage
        run: |
          hatch run test.py3.13:pytest -n 5 --cov --cov-fail-under=90
