name: Check for TODOs in code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for TODOs in the code
        run: ./check_todos.sh
